version: '3.9'

services:
  backend:
    build: ./soloflow-backend
    container_name: soloflow-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./soloflow-frontend
    container_name: soloflow-frontend
    restart: always
    ports:
      - "8080:80"
